---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
        uses: php-actions/composer@v5
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3        